version: '3.9'

services:
  mysql-db:
    image: mysql:latest
    networks:
      - back-end
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "0"
      MYSQL_RANDOM_ROOT_PASSWORD: "0"
    deploy:
      restart_policy:
        condition: on-failure

  api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - back-end
    ports:
      - "8080:8080"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  mysql-data:
    driver: local

networks:
  back-end:
    external: true
